founder:
  basic_update:
    - mariadb
    - phpmyadmin
    - nzbhydra
    - php-apache
    - jdownloader2
    - pyload
    - immich
    - duplicati
    - n8n
    - adguardhome
    - adguardhome-sync
    #- nocodb
    #- podgrab
    #- tanoshi
    #- music_stack
    #- n.eko
    #- romm
    #- bookstack
    #- freshrss
  manual_update:
    - jenkins
    - retrobot
    - changedetection.io
    - azuracast
  compose_path: /disks/storage/docker-compose/founder
vox:
  basic_update:
    - bazarr
    - tdarr
    - media_hosting
    - emby
    - it-tools
    - drawio
    - library
    - nextcloud
    - ombi
    - jackett
    - homarr
    - adguardhome
    #- gitea
    #- photoprism
  # manual_update:
  #   -
  compose_path: /disks/storage/docker-compose/vox
dewitt:
  basic_update:
    - komga
    - php-apache
    - audiobookshelf
    #- ghost
  manual_update:
    - mastodon
    - lemmy
  compose_path: /disks/Square/docker-compose/square